local addonName, addon = ...;
local cmdList = addon.cmd.list;

SLASH_AH_BUY1 = addon.cmd.list.BUY.DEFAULT;
SLASH_AH_BUY2 = addon.cmd.list.BUY.SHORT;

SLASH_AH_HELP1 = cmdList.HELP.DEFAULT;
SLASH_AH_HELP2 = cmdList.HELP.SHORT;

SLASH_AH_REFRESH1 = cmdList.REFRESH.DEFAULT;
SLASH_AH_REFRESH2 = cmdList.REFRESH.SHORT;

SLASH_AH_UNDERCUT1 = cmdList.UNDERCUT.DEFAULT;
SLASH_AH_UNDERCUT2 = cmdList.UNDERCUT.SHORT;
